#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BusTrack.Resource", IsApplication=true)]

namespace BusTrack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int holo_light_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconAddNetwork = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int iconLogout = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iconMap = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconNetworks = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconOptions = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iconStats = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int FlyOutContainer = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int FlyOutContent = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int FlyOutMenu = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int MenuButton = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int addNetwork = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int button1 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int button2 = 2131165193;
			
			// aapt resource value: 0x7f070024
			public const int clearButton = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int dataLimit = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int deleteAccount = 2131165223;
			
			// aapt resource value: 0x7f070003
			public const int editText1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int editText2 = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int frameLayout1 = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int imageView1 = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int imageView2 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int imageView3 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int imageView4 = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int imageView5 = 2131165217;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout2 = 2131165188;
			
			// aapt resource value: 0x7f070011
			public const int listView1 = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int logout = 2131165216;
			
			// aapt resource value: 0x7f070014
			public const int mainView = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int map = 2131165202;
			
			// aapt resource value: 0x7f070026
			public const int modifyAccount = 2131165222;
			
			// aapt resource value: 0x7f070000
			public const int radioGroup1 = 2131165184;
			
			// aapt resource value: 0x7f070016
			public const int recentStats = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int showMap = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int showOptions = 2131165212;
			
			// aapt resource value: 0x7f070028
			public const int tableLayout1 = 2131165224;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int textView3 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int textView4 = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int textView5 = 2131165214;
			
			// aapt resource value: 0x7f070022
			public const int textView6 = 2131165218;
			
			// aapt resource value: 0x7f070029
			public const int textViewAdapter = 2131165225;
			
			// aapt resource value: 0x7f070008
			public const int view1 = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int view2 = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int view3 = 2131165198;
			
			// aapt resource value: 0x7f070025
			public const int view4 = 2131165221;
			
			// aapt resource value: 0x7f07001f
			public const int view5 = 2131165215;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LineChooser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LineCreator = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MapLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MenuLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Options = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int OptionsLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Stats = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int StatsLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TextViewAdapter = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int PasswordHint = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int UsernameHint = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBarThemeText = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int MainTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
