#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BusTrack.Resource", IsApplication=true)]

namespace BusTrack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconAddNetwork = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int iconLogout = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iconMap = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconNetworks = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconOptions = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iconStats = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int FlyOutContainer = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int FlyOutContent = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int FlyOutMenu = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int MenuButton = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int button1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int button2 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int editText1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int editText2 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int frameLayout1 = 2131034120;
			
			// aapt resource value: 0x7f05001f
			public const int gridView1 = 2131034143;
			
			// aapt resource value: 0x7f050011
			public const int imageView1 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int imageView2 = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int imageView3 = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int imageView4 = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int imageView5 = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int listView1 = 2131034126;
			
			// aapt resource value: 0x7f05001c
			public const int logout = 2131034140;
			
			// aapt resource value: 0x7f050010
			public const int mainView = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int recentStats = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int showMap = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int showOptions = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int textView1 = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int textView2 = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int textView3 = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int textView4 = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int textView5 = 2131034138;
			
			// aapt resource value: 0x7f05001e
			public const int textView6 = 2131034142;
			
			// aapt resource value: 0x7f050004
			public const int view1 = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int view2 = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int view3 = 2131034123;
			
			// aapt resource value: 0x7f05001b
			public const int view5 = 2131034139;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Stats = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StatsLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int PasswordHint = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int UsernameHint = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
